### ISSUE TITLE
type error on query field of graphene.Schema()

### ISSUE THREAD

**Issue by skewty** [goodking-bq/graphene-sqlalchemy-auto#1]
`app.add_route("/", GraphQLApp(schema=graphene.Schema(query=Query, mutation=Mutation)))`
gives type error on query parameter in PyCharm.

Expected type `ObjectType` got type `GraphQLQuery` instead.

Is the type hint / expectation of graphene_sqlalchemy incorrect (upstream issue)?
Are you seeing a type error as well?

**Comment by skewty** [comment]
https://github.com/graphql-python/graphene/issues/1100

**Comment by goodking-bq** [comment]
the graphene's last version is 3.0b2,update to it can resolve .
but the version is also beta version ,i had not test .
